# Generated by Django 2.0 on 2018-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('customer_id', models.IntegerField(verbose_name='任务id')),
                ('create_time', models.CharField(max_length=255, verbose_name='分配时间')),
            ],
            options={
                'verbose_name': '任务库表',
                'verbose_name_plural': '任务库表',
                'db_table': 'ys_sale_customer',
                'ordering': ['-create_time'],
            },
        ),
    ]
