# Generated by Django 2.0 on 2018-04-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customeruser',
            table='ys_sale_customer',
        ),
    ]
