# Generated by Django 2.0 on 2018-04-13 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='公司名')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司域名')),
                ('company_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司类型')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='手机号')),
                ('qq', models.CharField(blank=True, max_length=255, null=True, verbose_name='QQ')),
                ('wechat', models.CharField(blank=True, max_length=255, null=True, verbose_name='微信号')),
                ('aike_status', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='爱客系统')),
                ('sem_status', models.IntegerField(default=0, verbose_name='sem客户')),
                ('useless_counter', models.IntegerField(default=0, verbose_name='无效次数')),
                ('city', models.TextField(blank=True, null=True, verbose_name='所在城市')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('randid', models.BigIntegerField(default=647888536, verbose_name='随机数')),
                ('keyword', models.CharField(blank=True, max_length=255, null=True, verbose_name='搜索关键词')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='签单金额')),
                ('depart', models.CharField(blank=True, max_length=255, null=True, verbose_name='负责销售部门')),
                ('sales', models.CharField(blank=True, max_length=255, null=True, verbose_name='负责销售人员')),
                ('business', models.IntegerField(default=0, verbose_name='商机')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SEOCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名称')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司域名')),
                ('link_man', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系人')),
                ('sex', models.CharField(blank=True, max_length=255, null=True, verbose_name='性别')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='职务')),
                ('tel_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='电话')),
                ('mobile_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='手机')),
                ('mobile_phone_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='手机归属地')),
                ('mobile_carrieroperator', models.CharField(blank=True, max_length=255, null=True, verbose_name='手机运营')),
                ('is_boss', models.CharField(blank=True, max_length=255, null=True, verbose_name='是否老总')),
                ('isboss_mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='老总手机')),
                ('legal_man', models.CharField(blank=True, max_length=255, null=True, verbose_name='法定代表')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='省份')),
                ('prefecture_level_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='地级市')),
                ('county_district', models.CharField(blank=True, max_length=255, null=True, verbose_name='县区')),
                ('address', models.TextField(blank=True, null=True, verbose_name='源地址')),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='邮编')),
                ('company_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司类型')),
                ('register_year', models.CharField(blank=True, max_length=255, null=True, verbose_name='注册年份')),
                ('register_month', models.CharField(blank=True, max_length=255, null=True, verbose_name='注册月份')),
                ('register_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='注册日子')),
                ('scope_business', models.TextField(blank=True, null=True, verbose_name='经营范围')),
                ('registration_authority', models.TextField(blank=True, null=True, verbose_name='登记机关')),
                ('issue_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='核准日期')),
                ('business_position', models.TextField(blank=True, null=True, verbose_name='经营现状')),
                ('aike_status', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否爱客')),
                ('seo_status', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否签约')),
                ('level', models.IntegerField(default=0, verbose_name='轮换次数')),
                ('rand_id', models.IntegerField(default=1658820307, verbose_name='随机数')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('produce_address', models.TextField(blank=True, null=True, verbose_name='生产经营地址')),
                ('finance_principal', models.CharField(blank=True, max_length=255, null=True, verbose_name='财务负责人姓名')),
                ('finance_principal_mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='财务负责人移动电话')),
                ('channel', models.CharField(blank=True, max_length=255, null=True, verbose_name='来源渠道：渠道1是原来的用户信息，渠道2是新导入的用户信息')),
            ],
            options={
                'verbose_name': 'seo资料库',
                'verbose_name_plural': 'seo资料库',
            },
        ),
        migrations.CreateModel(
            name='FormCustomerImport',
            fields=[
            ],
            options={
                'verbose_name': '资料导入',
                'verbose_name_plural': '资料导入',
                'proxy': True,
                'indexes': [],
            },
            bases=('customers.formcustomer',),
        ),
        migrations.CreateModel(
            name='NewFormCustomer',
            fields=[
            ],
            options={
                'verbose_name': '最新资料',
                'verbose_name_plural': '最新资料',
                'proxy': True,
                'indexes': [],
            },
            bases=('customers.formcustomer',),
        ),
    ]
