# Generated by Django 2.0 on 2018-04-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20180413_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcustomer',
            name='randid',
            field=models.BigIntegerField(default=1662023654, verbose_name='随机数'),
        ),
        migrations.AlterField(
            model_name='seocustomer',
            name='rand_id',
            field=models.IntegerField(default=2071715150, verbose_name='随机数'),
        ),
        migrations.AlterModelTable(
            name='formcustomer',
            table='form_customer',
        ),
        migrations.AlterModelTable(
            name='seocustomer',
            table='seo_customer',
        ),
    ]
