# Generated by Django 2.0 on 2018-04-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20180413_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcustomer',
            name='randid',
            field=models.BigIntegerField(default=1017340171, verbose_name='随机数'),
        ),
        migrations.AlterField(
            model_name='seocustomer',
            name='rand_id',
            field=models.IntegerField(default=1610192519, verbose_name='随机数'),
        ),
    ]
