# Generated by Django 2.0 on 2018-05-04 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20180417_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessCustomer',
            fields=[
            ],
            options={
                'verbose_name': '成功案例',
                'verbose_name_plural': '成功案例',
                'proxy': True,
                'indexes': [],
            },
            bases=('customers.formcustomer',),
        ),
        migrations.AlterField(
            model_name='formcustomer',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='首次发现'),
        ),
        migrations.AlterField(
            model_name='formcustomer',
            name='randid',
            field=models.BigIntegerField(default=1354361955, verbose_name='随机数'),
        ),
        migrations.AlterField(
            model_name='formcustomer',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='最后发现'),
        ),
        migrations.AlterField(
            model_name='seocustomer',
            name='rand_id',
            field=models.IntegerField(default=488747755, verbose_name='随机数'),
        ),
    ]
