# Generated by Django 2.0 on 2018-05-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='渠道来源')),
            ],
            options={
                'verbose_name': '渠道信息',
                'verbose_name_plural': '渠道信息',
                'db_table': 'ys_channel',
            },
        ),
    ]
