# Generated by Django 2.0 on 2018-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormRegionCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='城市')),
            ],
            options={
                'verbose_name': '城市信息',
                'verbose_name_plural': '城市信息',
                'db_table': 'ys_city',
            },
        ),
    ]
