# Generated by Django 2.0 on 2018-08-10 09:50

import datetime
from django.db import migrations, models
import trainmaterial.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainmaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_type', models.CharField(max_length=255, verbose_name='培训类型')),
                ('train_file', models.FileField(help_text='请选择不大于50M的文档', upload_to='trainFiles/', validators=[trainmaterial.validators.validate_file_extension], verbose_name='培训文件')),
                ('train_remark', models.TextField(blank=True, null=True, verbose_name='备注说明')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '培训文件',
                'verbose_name_plural': '培训文件',
                'db_table': 'ys_trainmaterial',
            },
        ),
    ]
