# Generated by Django 2.0 on 2018-04-13 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcount',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 17, 49, 45, 696935), verbose_name='点击时间'),
        ),
        migrations.AlterModelTable(
            name='formcount',
            table='form_count',
        ),
        migrations.AlterModelTable(
            name='formcounttotal',
            table='form_count_total',
        ),
    ]
