# Generated by Django 2.0 on 2018-05-05 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counts', '0002_auto_20180413_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcount',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 15, 3, 5, 580575), verbose_name='点击时间'),
        ),
        migrations.AlterModelTable(
            name='formcount',
            table='form_count_details',
        ),
    ]
