# Generated by Django 2.0 on 2018-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountByDepart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=255, verbose_name='销售部门')),
                ('total_amount', models.IntegerField(verbose_name='签单金额')),
                ('total_business', models.IntegerField(verbose_name='商机')),
                ('total_amountNum', models.IntegerField(verbose_name='签单数量')),
                ('create_time', models.DateTimeField(verbose_name='统计时间')),
            ],
            options={
                'verbose_name': '销售部门统计',
                'verbose_name_plural': '销售部门统计',
                'db_table': 'ys_count_by_depart',
            },
        ),
        migrations.CreateModel(
            name='CountBySale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.CharField(max_length=255, verbose_name='销售人员')),
                ('total_amount', models.IntegerField(verbose_name='签单金额')),
                ('total_business', models.IntegerField(verbose_name='商机')),
                ('total_amountNum', models.IntegerField(verbose_name='签单数量')),
                ('create_time', models.DateTimeField(verbose_name='统计时间')),
            ],
            options={
                'verbose_name': '销售人员统计',
                'verbose_name_plural': '销售人员统计',
                'db_table': 'ys_count_by_sale',
            },
        ),
        migrations.CreateModel(
            name='addUpByDepart',
            fields=[
            ],
            options={
                'verbose_name': '部门销售统计',
                'verbose_name_plural': '部门销售统计',
                'proxy': True,
                'indexes': [],
            },
            bases=('customers.formcustomer',),
        ),
    ]
