# Generated by Django 2.0 on 2018-04-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addUpByDepart',
            fields=[
            ],
            options={
                'verbose_name': '部门销售统计',
                'verbose_name_plural': '部门销售统计',
                'proxy': True,
                'indexes': [],
            },
            bases=('customers.formcustomer',),
        ),
    ]
