# Generated by Django 2.0 on 2018-04-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdeaprt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdeaprt',
            name='depart',
        ),
        migrations.RemoveField(
            model_name='userdeaprt',
            name='user',
        ),
        migrations.DeleteModel(
            name='userDeaprt',
        ),
    ]
