# Generated by Django 2.0 on 2018-04-14 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180413_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='depart',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='departs.TSDepart', verbose_name='所有部门'),
        ),
    ]
