# Generated by Django 2.0 on 2018-05-09 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TSDepart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departname', models.CharField(max_length=100, verbose_name='部门名称')),
                ('description', models.CharField(max_length=100, verbose_name='部门描述')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='departs.TSDepart', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门组织',
                'verbose_name_plural': '部门组织',
                'db_table': 'ys_depart',
            },
        ),
    ]
