# Generated by Django 2.0 on 2018-05-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='参数名')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='参数值')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '参数信息',
                'verbose_name_plural': '参数信息',
                'db_table': 'ys_constants',
            },
        ),
    ]
