# Generated by Django 2.0 on 2018-06-07 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speechcraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speechTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='话术对应标题')),
                ('speechTarget', models.CharField(max_length=255, verbose_name='话术适用对象', null=True, blank=True)),
                ('speechKeyword', models.TextField(blank=True, max_length=255, null=True, verbose_name='话术对应关键词')),
                ('speechQuestion', models.CharField(blank=True, max_length=255, null=True, verbose_name='话术对应问题')),
                ('speechFlow', models.TextField(blank=True, null=True, verbose_name='话术对应流程')),
                ('speechAnswer', models.TextField(blank=True, null=True, verbose_name='话术对应内容')),
                ('speechGoal', models.TextField(blank=True, null=True, verbose_name='话术对应目的')),
                ('speechLabel', models.CharField(blank=False, max_length=255, null=False, verbose_name='话术对应类型')),
                ('speechRemark', models.TextField(blank=True, null=True, verbose_name='话术对应备注')),
                ('speechCount', models.IntegerField(default=0, verbose_name='话术查看次数')),
                ('speechCreateTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='话术创建时间')),
                ('speechUpdateTime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='话术更新时间')),
            ],
            options={
                'verbose_name': '话术范例',
                'verbose_name_plural': '话术范例',
                'db_table': 'ys_speechcraft',
            },
        ),
    ]
