# Generated by Django 2.0 on 2018-06-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechcraft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechcraftShow',
            fields=[
            ],
            options={
                'verbose_name': '话术查看',
                'verbose_name_plural': '话术查看',
                'proxy': True,
                'indexes': [],
            },
            bases=('speechcraft.speechcraft',),
        ),
        migrations.AlterField(
            model_name='speechcraft',
            name='speechLabel',
            field=models.CharField(choices=[('开场白', '开场白'), ('激发兴趣', '激发兴趣'), ('挖掘需求', '挖掘需求'), ('导入产品', '导入产品'), ('邀约见面', '邀约见面'), ('疑难解答', '疑难解答'), ('知识普及', '知识普及')], max_length=255, verbose_name='话术对应类型'),
        ),
    ]
